# Generated by Django 3.2 on 2021-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=256)),
                ('exchange', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('w52high', models.DecimalField(decimal_places=2, max_digits=19)),
                ('w52low', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ytdchange', models.DecimalField(decimal_places=2, max_digits=19)),
                ('marketcap', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('peratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('popen', models.DecimalField(decimal_places=2, max_digits=19)),
                ('low', models.DecimalField(decimal_places=2, max_digits=19)),
                ('high', models.DecimalField(decimal_places=2, max_digits=19)),
                ('close', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
