# Generated by Django 3.2 on 2021-04-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_alter_quote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
