# Generated by Django 3.2 on 2021-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0003_auto_20210419_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='marketcap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='peratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='popen',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='w52high',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='w52low',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='ytdchange',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
