# Generated by Django 3.2 on 2021-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0004_auto_20210419_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
