# Generated by Django 3.2 on 2021-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0005_alter_quote_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
